document.getElementById('run').onclick=()=>{
 const lines=[],assert=(v,msg='Unexpected result')=>{if(!v)throw Error(msg);},test=(name,fn)=>{try{fn();lines.push('PASS '+name);}catch(e){lines.push('FAIL '+name+' — '+e.message);}};
 const mc=MarketClock,us=mc.profiles.find(p=>p.id==='us'),fx=mc.profiles.find(p=>p.id==='fx'),crypto=mc.profiles.find(p=>p.id==='crypto'),ms=s=>Date.parse(s),iso=n=>new Date(n).toISOString();
 test('US regular session begins at 09:30 New York',()=>{const t=ms('2026-09-14T13:30:00Z');assert(mc.status(us,t).open);assert(!mc.status(us,t-1).open);});
 test('US regular close is exclusive',()=>assert(!mc.status(us,ms('2026-09-14T20:00:00Z')).open));
 test('US weekend points to Monday',()=>assert(iso(mc.status(us,ms('2026-09-12T15:00:00Z')).next)==='2026-09-14T13:30:00.000Z'));
 test('Labor Day is closed, next open Tuesday',()=>{const s=mc.status(us,ms('2026-09-07T15:00:00Z'));assert(s.label==='Exchange holiday');assert(iso(s.next)==='2026-09-08T13:30:00.000Z');});
 test('Thanksgiving early close ends at 13:00 ET',()=>{const s=mc.status(us,ms('2026-11-27T15:00:00Z'));assert(iso(s.next)==='2026-11-27T18:00:00.000Z');});
 test('Christmas Eve early close',()=>assert(iso(mc.status(us,ms('2026-12-24T15:00:00Z')).next)==='2026-12-24T18:00:00.000Z'));
 test('July 2 2026 is a full session, not an invented early close',()=>assert(iso(mc.status(us,ms('2026-07-02T15:00:00Z')).next)==='2026-07-02T20:00:00.000Z'));
 test('US winter open adjusts for daylight saving',()=>assert(iso(mc.status(us,ms('2026-11-09T10:00:00Z')).next)==='2026-11-09T14:30:00.000Z'));
 test('US/Europe DST mismatch does not shift New York open',()=>assert(iso(mc.status(us,ms('2026-03-16T10:00:00Z')).next)==='2026-03-16T13:30:00.000Z'));
 test('Unverified calendar years do not invent schedules',()=>assert(mc.status(us,ms('2029-01-02T15:00:00Z')).next===null));
 test('FX midnight is not a close while adjacent sessions continue',()=>assert(iso(mc.status(fx,ms('2026-09-14T12:00:00Z')).next)==='2026-09-18T20:58:00.000Z'));
 test('Broker winter and summer server times differ',()=>{assert(iso(mc.instant('2026-01-05',600,'Europe/Helsinki'))==='2026-01-05T08:00:00.000Z');assert(iso(mc.instant('2026-09-14',600,'Europe/Helsinki'))==='2026-09-14T07:00:00.000Z');});
 test('BTCXAU is closed during the weekend',()=>assert(!mc.status(crypto,ms('2026-09-12T14:00:00Z'),'BTCXAU.s').open));
 test('Sunday crypto maintenance gap is respected',()=>assert(!mc.status(crypto,ms('2026-09-12T21:10:00Z'),'ETHUSD.s').open));
 test('Brent opening differs from WTI',()=>{const p=mc.profiles.find(p=>p.id==='energy'),n=ms('2026-09-14T23:00:00Z');assert(mc.status(p,n,'WTI.s').open);assert(!mc.status(p,n,'BRENT.s').open);});
 test('European stock symbols do not become US shares',()=>{assert(mc.group('AIRF')==='eu');assert(mc.group('ADSGn')==='eu');assert(mc.group('AAPL')==='us');});
 test('Countdown includes days as hours and never goes negative',()=>{assert(mc.duration(-1)==='00:00:00');assert(mc.duration(90061000)==='25:01:01');});
 const trade={bot:'a',sym:'ETHUSD.m',tf:'15m',dir:1,pnl:-5,r:-.5,score:70,touched:true,entryTime:ms('2026-09-14T14:00:00Z'),exitTime:ms('2026-09-14T15:00:00Z'),reason:'stop-loss',note:'special setup'};
 test('Combined direction, outcome, score and hold filters',()=>{assert(TradeReview.match(trade,{side:'buy',outcome:'loss',score:'70',holdmin:'60',holdmax:'60'}));assert(!TradeReview.match(trade,{side:'sell'}));});
 test('Zero is a real numeric filter, not an empty input',()=>{assert(!TradeReview.match(trade,{min:'0'}));assert(TradeReview.match(trade,{max:'0'}));});
 test('Date bounds include both endpoint days',()=>{assert(TradeReview.match(trade,{from:'2026-09-14',to:'2026-09-14'}));assert(!TradeReview.match(trade,{from:'2026-09-15'}));});
 test('Missing R does not pass a numeric R filter',()=>assert(!TradeReview.match({...trade,r:null},{rmin:'-1'})));
 test('Hand-adjusted and text search combine',()=>{assert(TradeReview.match(trade,{touched:'yes',query:'SPECIAL'}));assert(!TradeReview.match(trade,{touched:'no'}));});
 test('Breakeven differs from losing trades',()=>{assert(TradeReview.match({...trade,pnl:0},{outcome:'flat'}));assert(!TradeReview.match({...trade,pnl:0},{outcome:'loss'}));});
 test('US company and index headlines reach the new filter',()=>{assert(MarketNews.classify({title:'Nvidia earnings lift Nasdaq',sourceId:'markets'}).tags.includes('US stocks'));assert(MarketNews.classify({title:'Federal Reserve cuts rates',sourceId:'fed'}).tags.includes('US stocks'));});
 test('European stocks do not automatically become US stock news',()=>assert(!MarketNews.classify({title:'European stocks climb after ECB decision',sourceId:'markets'}).tags.includes('US stocks')));
 test('Null price stays unavailable instead of displaying zero',()=>assert(TradeReview.fmt(null)==='—'));
 document.getElementById('results').textContent=lines.join('\n')+'\n\n'+lines.filter(s=>s.startsWith('PASS')).length+'/'+lines.length+' passed';
};
